#!/bin/bash
#
# This file was automatically generated by s2e-env at {{ current_time | datetimefilter }}
#
# This bootstrap file is used to control the execution of the Linux target
# program in S2E.
#
# When you run launch-s2e.sh, the guest VM calls s2eget to fetch and execute this
# bootstrap script. This bootstrap script and the S2E config file determine how
# the target program is analyzed.
#

# To save you the hassle of rebuilding the image every time you want to update
# S2E's guest tools, the first thing that we do is get the latest versions of
# the guest tools.
function update_guest_tools {
    GUEST_TOOLS="s2e.so cgccmd s2ecmd s2eget s2eput"
    for TOOL in ${GUEST_TOOLS}; do
        ./s2eget guest-tools/${TOOL}
        chmod +x ${TOOL}
    done
}
