#!/bin/bash
#
# This file was automatically generated by s2e-env at
# {{ current_time | datetimefilter }}
#
# This script can be used to make persistent changes to the virtual machine
# image. Additional QEMU command line arguments can be passed to this script at
# run time
#

{{ env_dir }}/bin/qemu-system-{{ arch }}                            \
    -m {{ memory }} -enable-kvm                                     \
    -drive file={{ image_path }},format=raw,cache=writeback $*

