#!/bin/bash
#
# This file was automatically generated by s2e-env at
# {{ current_time | datetimefilter }}
#
# This script can be used to run an S2E image in non-S2E mode, e.g. to take a
# snapshot. Additional QEMU command line arguments can be passed to this script
# at run time
#

LD_PRELOAD={{ install_dir }}/share/libs2e/libs2e-{{ arch }}.so      \
    {{ install_dir }}/bin/qemu-system-{{ arch }}                    \
    -k en-us -m {{ memory }} -enable-kvm                            \
    -drive file={{ image_path }},format=s2e,cache=writeback         \
    -serial file:serial.txt {{ qemu_extra_flags }} $*
