#
# This file was automatically generated by s2e-env at {{ creation_time }}
#
# This file must be used with "source s2e_activate" *from bash*; you cannot run
# it directly.
#
# Sourcing this file will set the S2EDIR environment variable, and allows you
# to use s2e commands from any directory. Sourcing this file also makes
# s2e_deactivate available, which unsets the S2E environment variables.
#

s2e_deactivate() {
    if ! [ -z "${_S2E_OLD_VIRTUAL_PS1+_}" ] ; then
        PS1="$_S2E_OLD_VIRTUAL_PS1"
        export PS1
        unset _S2E_OLD_VIRTUAL_PS1
    fi

    unset S2EDIR

    if [ ! "${1-}" = "nondestructive" ] ; then
        # Self destruct!
        unset -f s2e_deactivate
    fi
}

# unset irrelvant variables
s2e_deactivate nondestructive

S2EDIR="{{ S2EDIR }}"
export S2EDIR

if [ -z "${S2E_ENV_DISABLE_PROMPT-}" ] ; then
    _S2E_OLD_VIRTUAL_PS1="$PS1"
    if [ "x" != x ] ; then
        PS1="$PS1"
    else
        PS1="[S2E:`basename \"$S2EDIR\"`] $PS1"
    fi
    export PS1
fi
